"""House Price Prediction Web Application

FastAPI app that loads a pre-trained model (model.pkl) and serves a small
HTML UI for predicting house prices from square footage.

Routes:
- GET /        : HTML form
- POST /predict: price prediction result
"""

from fastapi import FastAPI, Form
from fastapi.responses import HTMLResponse
import joblib
import numpy as np

# Create the FastAPI application instance
app = FastAPI()

# Load the trained model generated by model-creation.py
model = joblib.load("model.pkl")


@app.get("/", response_class=HTMLResponse)
def Home():
    """Serve the home page with the house area input form."""
    return """
    <html>
        <head>
            <title>House Price Predictor</title>
            <link rel="icon" href="/static/favicon.ico">
        </head>
        <body>
            <h2>House Price Prediction</h2>
            <form action="/predict" method="post">
                <label>Enter Area (sq ft):</label>
                <input type="number" name="area" required>
                <button type="submit">Predict</button>
            </form>
        </body>
    </html>
    """


@app.post("/predict", response_class=HTMLResponse)
def predict(area: float = Form(...)):
    """Predict house price based on the provided area (in sq ft)."""
    prediction = model.predict(np.array([[area]]))[0]
    return f"""
    <html>
        <body>
            <h2>Predicted Price: ${prediction:,.2f}</h2>
            <a href="/">Go Back</a>
        </body>
    </html>
    """
